name: Task Manager CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend-build-test:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: matar
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build backend
        working-directory: backend
        run: mvn clean install

  frontend-build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

  docker-build-push:

    runs-on: ubuntu-latest
    needs: [backend-build-test, frontend-build]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build -t bachirc934/task-manager-backend:latest ./backend

      - name: Build frontend Docker image
        run: |
          docker build -t bachirc934/task-manager-frontend:latest ./frontend

      - name: Push backend image
        run: |
          docker push bachirc934/task-manager-backend:latest

      - name: Push frontend image
        run: |
          docker push bachirc934/task-manager-frontend:latest